
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 13 21:20:55 MDT 2021
//----------------------------------------------------

package Codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bool = 22;
  public static final int podri = 38;
  public static final int comp = 60;
  public static final int Entero = 4;
  public static final int corch_der = 52;
  public static final int suma = 61;
  public static final int resta = 59;
  public static final int dif = 68;
  public static final int loop = 23;
  public static final int main = 43;
  public static final int nes = 42;
  public static final int mod = 51;
  public static final int asig = 49;
  public static final int compare = 41;
  public static final int enable = 37;
  public static final int getPort = 32;
  public static final int exception = 35;
  public static final int llave_der = 54;
  public static final int joy = 21;
  public static final int message = 29;
  public static final int swing = 25;
  public static final int verify = 27;
  public static final int pressed = 17;
  public static final int negative = 40;
  public static final int key = 10;
  public static final int kill = 12;
  public static final int par_der = 56;
  public static final int invert = 18;
  public static final int shatter = 24;
  public static final int Flotante = 5;
  public static final int Cadena = 3;
  public static final int then = 8;
  public static final int menor = 47;
  public static final int EOF = 0;
  public static final int mayor_igual = 44;
  public static final int error = 1;
  public static final int resurrect = 13;
  public static final int hold = 16;
  public static final int mayor = 46;
  public static final int positive = 39;
  public static final int fn = 7;
  public static final int or = 62;
  public static final int corch_izq = 53;
  public static final int reco = 31;
  public static final int btn = 11;
  public static final int ERROR = 6;
  public static final int menor_igual = 45;
  public static final int cast = 28;
  public static final int res_asig = 58;
  public static final int incremento = 63;
  public static final int sum_asig = 67;
  public static final int option = 26;
  public static final int multi = 48;
  public static final int word = 34;
  public static final int getY = 20;
  public static final int Identificador = 2;
  public static final int llave_izq = 55;
  public static final int getX = 19;
  public static final int not = 66;
  public static final int and = 65;
  public static final int decremento = 64;
  public static final int getFunc = 15;
  public static final int Array = 33;
  public static final int getP = 30;
  public static final int setFunc = 14;
  public static final int div = 50;
  public static final int getButton = 36;
  public static final int decimal = 9;
  public static final int par_izq = 57;
}

